name: linux

on:
  push:https://github.com/ColleagueRiley/RPhys
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt-update
      run: sudo apt-get update
    - name: apt
      run: sudo apt-get install mesa-common-dev libglx-dev libxcursor-dev   
    - name: gcc
      run: gcc example/main.c -DRSGL_IMPLEMENTATION -lX11 -lGLX -lGL -lm
